### ISSUE TITLE
'int android.graphics.Rect.width()

### ISSUE THREAD

**Issue by coderxiaotu** [penfeizhou/APNG4Android#101]
版本：
com.github.penfeizhou.android.animation:apng:2.10.0
使用：
APNGDrawable  tabDrawable = APNGDrawable.fromAsset(context, "tabs/my.apng");

Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.width()' on a null object reference
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.a(FrameSeqDecoder.java:14)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.c(FrameSeqDecoder.java:2)
	at c.j.c.a.c.setBounds(FrameAnimationDrawable.java:2)
	at com.xx.xx.MainActivity$5$1.run(MainActivity.java:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8387)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Back traces ends.
报错比较频繁

**Comment by penfeizhou** [comment]
请贴出混淆前的代码堆栈

**Comment by coderxiaotu** [comment]
<img width="666" alt="企业微信截图_b356d7d2-43b7-4488-b529-8d52beeb506e" src="https://user-images.githubusercontent.com/10681464/118599151-b2c96600-b7e1-11eb-8a8f-e42f6b8a8322.png">

**Comment by penfeizhou** [comment]
目前判断可能是图片格式存在问题,解析尺寸信息时出现异常.
方便的话可以提供下这个图片及使用代码吗?
