### ISSUE TITLE
使用Glide插件时加载部分网络图片报错 java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409

### ISSUE THREAD

**Issue by liuhuan8986** [penfeizhou/APNG4Android#105]
### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  |  Huawei 荣耀V20                               |      |
| System Version               |  10                                            |      |
| APNG4Android Library Version |   2.10.0                                           |      |
| Repro rate                   |  all the time (100%)    |      |
| Repro with our demo project  | 没有用demo试过            |      |
| Glide版本 | 4.11.0           |      |

### Issue Description and Steps

System.err: java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
     at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:78)
     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
     at java.io.FilterInputStream.read(FilterInputStream.java:133)
     at com.github.penfeizhou.animation.io.StreamReader.read(StreamReader.java:32)
     at com.github.penfeizhou.animation.io.FilterReader.read(FilterReader.java:40)
     at com.github.penfeizhou.animation.webp.io.WebPReader.getFourCC(WebPReader.java:62)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.parseChunk(WebPParser.java:124)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.isAWebP(WebPParser.java:92)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:35)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
     at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
     at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:57)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:929)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
 java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
     at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:78)
     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
     at java.io.FilterInputStream.read(FilterInputStream.java:133)
     at com.github.penfeizhou.animation.io.StreamReader.read(StreamReader.java:32)
     at com.github.penfeizhou.animation.io.FilterReader.read(FilterReader.java:40)
     at com.github.penfeizhou.animation.apng.io.APNGReader.readFourCC(APNGReader.java:66)
     at com.github.penfeizhou.animation.apng.io.APNGReader.matchFourCC(APNGReader.java:55)
     at com.github.penfeizhou.animation.apng.decode.APNGParser.isAPNG(APNGParser.java:84)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:36)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
     at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
     at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:57)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:929)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
 java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
     at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:78)
     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:230)
     at java.io.FilterInputStream.read(FilterInputStream.java:83)
     at com.github.penfeizhou.animation.io.StreamReader.peek(StreamReader.java:25)
     at com.github.penfeizhou.animation.io.FilterReader.peek(FilterReader.java:25)
     at com.github.penfeizhou.animation.gif.decode.GifParser.checkHeader(GifParser.java:131)
     at com.github.penfeizhou.animation.gif.decode.GifParser.isGif(GifParser.java:84)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:37)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
     at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
     at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:57)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:929)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
Glide: Load failed for https://p9-open.onewsimg.com/img/pgc-image/253777f972b04d0e878b8dff5eb1b259~tplv-tt-cs0:960:540.webp?from=feed with size [978x576]

class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 3 causes:
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ContentLengthInputStream->Object->Drawable}, REMOTE
    There were 3 causes:
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->FrameSeqDecoder->Drawable}
        Cause (2 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->GifDrawable->Drawable}
    There was 1 cause:
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
        Cause (3 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->Bitmap->Drawable}
    There was 1 cause:
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
        Cause (4 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->BitmapDrawable->Drawable}
    There was 1 cause:
    java.io.IOException(Failed to read all expected data, expected: 64908, but read: 23409)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
		  
System.err: java.io.IOException: Out of chunk area
     at com.github.penfeizhou.animation.webp.decode.BaseChunk.parse(BaseChunk.java:41)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.parseChunk(WebPParser.java:151)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.isAWebP(WebPParser.java:92)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:35)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
     at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
     at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:57)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:929)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
 java.io.IOException: Out of chunk area
     at com.github.penfeizhou.animation.webp.decode.BaseChunk.parse(BaseChunk.java:41)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.parseChunk(WebPParser.java:151)
     at com.github.penfeizhou.animation.webp.decode.WebPParser.isAWebP(WebPParser.java:92)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:35)
     at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
     at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
     at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:57)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:929)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)

**Comment by penfeizhou** [comment]
这是Glide层读出的InputStream流的问题,请查看其他代码设置是否有问题.
java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:78)
at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:230)
at java.io.FilterInputStream.read(FilterInputStream.java:83)
at com.github.penfeizhou.animation.io.StreamReader.peek(StreamReader.java:25)
at com.github.penfeizhou.animation.io.FilterReader.peek(FilterReader.java:25)
at com.github.penfeizhou.animation.gif.decode.GifParser.checkHeader(GifParser.java:131)
at com.github.penfeizhou.animation.gif.decode.GifParser.isGif(GifParser.java:84)
at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:37)
at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)

**Comment by liuhuan8986** [comment]
不应该啊，不用这个库的插件就没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月19日(周一) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [penfeizhou/APNG4Android] 使用Glide插件时加载部分网络图片报错 java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409 (#105)




 
这是Glide层读出的InputStream流的问题,请查看其他代码设置是否有问题.
 java.io.IOException: Failed to read all expected data, expected: 64908, but read: 23409
 at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:78)
 at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
 at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
 at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:230)
 at java.io.FilterInputStream.read(FilterInputStream.java:83)
 at com.github.penfeizhou.animation.io.StreamReader.peek(StreamReader.java:25)
 at com.github.penfeizhou.animation.io.FilterReader.peek(FilterReader.java:25)
 at com.github.penfeizhou.animation.gif.decode.GifParser.checkHeader(GifParser.java:131)
 at com.github.penfeizhou.animation.gif.decode.GifParser.isGif(GifParser.java:84)
 at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:37)
 at com.github.penfeizhou.animation.glide.StreamAnimationDecoder.handles(StreamAnimationDecoder.java:25)
 at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)

**Comment by liuhuan8986** [comment]
我就正常的使用Glide加载，加了3个依赖库

**Comment by penfeizhou** [comment]
您可以用这个项目的demo工程运行下试试看是否有问题.

**Comment by penfeizhou** [comment]
在这里加上您图片的URL :
https://github.com/penfeizhou/APNG4Android/blob/master/app/src/main/java/com/github/penfeizhou/animation/demo/APNGTestActivity.java

**Comment by liuhuan8986** [comment]
> 在这里加上您图片的URL :
> https://github.com/penfeizhou/APNG4Android/blob/master/app/src/main/java/com/github/penfeizhou/animation/demo/APNGTestActivity.java

在这里单独的使用没有问题，但是我就是不明白，为什么在列表里，大量使用不同的图片的时候，就有部分加载失败的，并且概率很大，不使用这个库就没事，现在我也定位不了问题

**Comment by penfeizhou** [comment]
问题是Glide生成的流有问题,这个库里会调用InputStream.read方法去读取内容.
您这边可以写一个能复现的demo代码,我这边才能定位.
或者您可以不要使用这个glide plugin,先把内容下完后再创建WebPDrawable.

**Comment by liuhuan8986** [comment]
嗯，先不使用glide plugin，已经能确定是Glide问题的话，要不要提个bug给Glide

**Comment by liuhuan8986** [comment]
我大概发现问题了，当我使用Glide.with(context).load(url).diskCacheStrategy(DiskCacheStrategy.RESOURCE).placeholder(resid).into(imageView)的时候，
就大概率出现加载失败的情况
而使用Glide.with(context).load(url).placeholder(resid).into(imageView);则没有问题，
估计是 设置了diskCacheStrategy(DiskCacheStrategy.RESOURCE)导致的
