### ISSUE TITLE
AnimationFrame IllegalArgumentException

### ISSUE THREAD

**Issue by yifleo** [penfeizhou/APNG4Android#106]
### New Issue Checklist

- 加载webp的时候crash了，麻烦看看

### Issue Info

| Info                         | Value                                                 |
| ---------------------------- | ----------------------------------------------------- |
| Device Info                  | samsung、oppo、xiaomi                                 |
| System Version               | 4.2.2,4.3                                             |
| APNG4Android Library Version | 2.1.0                                                 |

### crash

Fatal Exception: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
       at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:525)
       at com.github.penfeizhou.animation.webp.decode.AnimationFrame.draw(AnimationFrame.java:83)
       at com.github.penfeizhou.animation.webp.decode.AnimationFrame.draw(AnimationFrame.java:21)
       at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:147)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:500)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:36)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:280)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by jingpeng** [comment]
资源图发下

**Comment by yifleo** [comment]
> 资源图发下

这个是在线上发生crash的，我们这边也确定不了是哪个资源图，不过可以看到crash都是发生在4.2.2和4.3版本的，5.0以下的版本加载会有问题吗

**Comment by yifleo** [comment]
这个问题我们之前尝试过修复，例如把APNGFrame类中的draw()方法修改如下,线上就没出现过crash了，不过这样需要我们引入整个库的代码而不是通过gradle依赖，维护比较麻烦：
`
@Override
    public Bitmap draw(Canvas canvas, Paint paint, int sampleSize, Bitmap reusedBitmap, APNGWriter writer) {
        try {
            ...
            Bitmap bitmap;
            try {
                bitmap = BitmapFactory.decodeByteArray(bytes, 0, length, options);
            } catch (IllegalArgumentException e) {
                e.printStackTrace();
                // Problem decoding into existing bitmap,这个异常我们不使用复用的Bitmap来加载图片。
                BitmapFactory.Options optionsFixed = new BitmapFactory.Options();
                optionsFixed.inJustDecodeBounds = false;
                optionsFixed.inSampleSize = sampleSize;
                optionsFixed.inMutable = true;
                bitmap = BitmapFactory.decodeByteArray(bytes, 0, length, optionsFixed);
            }
			...
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
`

**Comment by jingpeng** [comment]
可以吧，我们merge并入

**Comment by yifleo** [comment]
> 可以吧，我们merge并入
大佬，是我这边把这段代码发起pull request的意思么

**Comment by jingpeng** [comment]
我这边改吧，因为frame有多处实现

**Comment by jingpeng** [comment]
[https://github.com/penfeizhou/APNG4Android/commit/f7ff4d10a2db5c20a38087d1cc0ed523b5ee7d7c](url)

**Comment by jingpeng** [comment]
@yifleo

**Comment by jingpeng** [comment]
2.11.0 release include this commit

**Comment by yifleo** [comment]
> 2.11.0 release include this commit

ok, thanks
