### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Xiaoben336** [penfeizhou/APNG4Android#107]
动画播放结束，继续播放动画
2021-07-28 20:54:48.147 10626-10803/ E/AndroidRuntime: FATAL EXCEPTION: FrameDecoderExecutor-0
    Process: com.didi.voyager.jarvis, PID: 10626
    java.lang.ArrayIndexOutOfBoundsException: length=33; index=-2
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:135)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:500)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by penfeizhou** [comment]
请问是怎么调用API的

动画播放结束，继续播放动画请先调用`reset`方法,然后再调用`start`方法

**Comment by penfeizhou** [comment]
先关闭,等待进一步反馈.
