### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by chenyunecjtu** [penfeizhou/APNG4Android#122]
在列表里通过glide加载web动画
E/DEBUG: java.lang.ArrayIndexOutOfBoundsException: length=33; index=-2
     at java.util.ArrayList.get(ArrayList.java:439)
 at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:135)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:500)
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
 at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)

**Comment by jingpeng** [comment]
库版本，样例代码贴一下？

**Comment by penfeizhou** [comment]
如果您提供更多信息,我们将继续跟进.

**Comment by penfeizhou** [comment]
v2.16.0修复该问题
