### ISSUE TITLE
Buffer not large enough for pixels

### ISSUE THREAD

**Issue by EasyDevWork** [penfeizhou/APNG4Android#133]
Thread Name: 'FrameDecoderExecutor-0'
Back traces starts.
java.lang.RuntimeException: Buffer not large enough for pixels
	at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:649)
	at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(SourceFile:6)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.u(SourceFile:6)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.d(SourceFile:1)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$a.run(SourceFile:4)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.s(SourceFile:14)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.l(SourceFile:1)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$f.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Back traces ends.

**Comment by penfeizhou** [comment]
Please provide using library version and problemed picture.

**Comment by EasyDevWork** [comment]
com.github.penfeizhou.android.animation:glide-plugin:2.12.0
com.github.penfeizhou.android.animation:awebp:2.12.0

**Comment by EasyDevWork** [comment]
http://xiyou.sc.diyixin.com/mall/pro/webp_open_upgrade_purple.webp
