### ISSUE TITLE
boolean android.graphics.Bitmap.isRecycled()

### ISSUE THREAD

**Issue by EasyDevWork** [penfeizhou/APNG4Android#134]
Thread Name: 'FrameDecoderExecutor-0'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:91)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:154)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1561)
	at com.github.penfeizhou.animation.webp.decode.AnimationFrame.draw(SourceFile:18)
	at com.github.penfeizhou.animation.webp.decode.AnimationFrame.draw(SourceFile:1)
	at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(SourceFile:19)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.u(SourceFile:6)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.d(SourceFile:1)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$a.run(SourceFile:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Back traces ends.

**Comment by penfeizhou** [comment]
Please provide using library version and problemed picture.

**Comment by EasyDevWork** [comment]
com.github.penfeizhou.android.animation:awebp:2.12.0
com.github.penfeizhou.android.animation:glide-plugin:2.12.0

**Comment by EasyDevWork** [comment]
http://xiyou.sc.diyixin.com/dev-img-energy/data/common/20211008141738007928580/webp_goods.webp

**Comment by EasyDevWork** [comment]
http://xiyou.sc.diyixin.com/mall/pro/webp_open_upgrade_purple.webp

**Comment by jingpeng** [comment]
update to 2.17.0 please, fixed some exception
