### ISSUE TITLE
Specific Gif causes crash

### ISSUE THREAD

**Issue by connyduck** [penfeizhou/APNG4Android#148]
[This gif](https://mk.absturztau.be/files/f9986a6c-31c8-49a2-845d-7a13aecc0525) causes the library to crash. I'm using the Glide integration, version 2.20.0

```
  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.width()' on a null object reference
        at com.github.penfeizhou.animation.gif.decode.GifDecoder.renderFrame(GifDecoder.java:113)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:505)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:280)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by jingpeng** [comment]
Can you paste the explicit gif file here?

**Comment by connyduck** [comment]
![3e2e282b-152f-4a70-8d1d-eb7797d002e3](https://user-images.githubusercontent.com/10157047/168217613-3f50070b-082b-4559-99f2-3389799b4e99.gif)

**Comment by connyduck** [comment]
@penfeizhou any chance you can take a look at this? 🥺

**Comment by penfeizhou** [comment]
OK, let me see.

**Comment by penfeizhou** [comment]
This gif file's Background Color Index is out of range. This should not happen.
I'll add some protection code.

**Comment by penfeizhou** [comment]
Please try v2.22.0

**Comment by connyduck** [comment]
Yes it works with 2.22.0, thank you
