### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ShowMeThe** [penfeizhou/APNG4Android#168]
| Info                         | Value                                                 |  
| ---------------------------- | ----------------------------------------------------- | 
| Device Info                  |   vivo X9                 |      |
| System Version               | 7.1.2                                            |   
| APNG4Android Library Version | v2.23 .0                                | 

```
       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:854)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:798)
	at com.github.penfeizhou.animation.FrameAnimationDrawable.onRender(FrameAnimationDrawable.java:228)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:64)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:317)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:287)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

```
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.initCanvasBounds(FrameSeqDecoder.java:250)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$700(FrameSeqDecoder.java:36)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$5.run(FrameSeqDecoder.java:233)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

比较极端的机器自身内存不足

**Comment by penfeizhou** [comment]
系统内存不足不是本库处理的范围.
