### ISSUE TITLE
onRender:Buffer not large enough for pixels

### ISSUE THREAD

**Issue by tudou0digua** [penfeizhou/APNG4Android#212]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e.g. 小米Mix 2s (android 10) / 荣耀magic5 (Android14)                               |      |
| System Version               | e.g.  10.0/14.0                                             |      |
| APNG4Android Library Version | e.g.  2.28.0                                           |      |
| Repro rate                   | e.g. all the time (100%)    |      |
| Repro with our demo project  | it happen with our demo project         |      |
| Demo project link            | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
1、ImageView 宽高比较小，apng图片宽高比imageView 大一点时
2、ImageView scaleType set fitXY
3、Glide 加载图失败，必现报错：onRender:Buffer not large enough for pixels （FrameAnimationDrawable -> onRender() 方法中报错）

复现代码：
1、图片 url：https://code.z01.com/elephant.png
2、glide 版本：4.13.2
3、代码：（修改：APNGTestActivity 中的代码）
        ImageView imageView = new ImageView(this);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(44 * 2, 44 * 2);
        layoutParams.bottomMargin = 50;
        layoutParams.topMargin = 50;
        imageView.setScaleType(ImageView.ScaleType.FIT_XY);
        linearLayout.addView(imageView, layoutParams);
        Glide.with(imageView)
                .load("https://code.z01.com/elephant.png")
                .into(imageView);

**Comment by Kuki93** [comment]
> 感谢反馈, 该问题已在v2.29.0 修复

3.0.1版本中还是有这个问题！！！
```
  Fatal Exception: java.lang.RuntimeException: Buffer not large enough for pixels
       at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:674)
       at com.github.penfeizhou.animation.FrameAnimationDrawable.onRender(FrameAnimationDrawable.java:234)
```
我看了下你的代码，和源码检测有点不一样。
```
if (byteBuffer.remaining() < this.bitmap.getByteCount()) {
            Log.e(TAG, "onRender:Buffer not large enough for pixels");
            return;
        }
        this.bitmap.copyPixelsFromBuffer(byteBuffer);
```
```
int elements = src.remaining();
        int shift;
        if (src instanceof ByteBuffer) {
            shift = 0;
        } else if (src instanceof ShortBuffer) {
            shift = 1;
        } else if (src instanceof IntBuffer) {
            shift = 2;
        } else {
            throw new RuntimeException("unsupported Buffer subclass");
        }

        long bufferBytes = (long) elements << shift;
        long bitmapBytes = getByteCount();

        if (bufferBytes < bitmapBytes) {
            throw new RuntimeException("Buffer not large enough for pixels");
        }
```
我贴的是Android14的源码，在Android 11 和 Android 14的机器上均发现这个问题。
