### ISSUE TITLE
APNG + Coil, can not display with memory cache policy

### ISSUE THREAD

**Issue by vokhuyetOz** [penfeizhou/APNG4Android#221]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | Samsung S9                               |      |
| System Version               | Android 8.0                                             |      |
| APNG4Android Library Version | 3.0.1                                          |      |
| Repro rate                   | all the time (100%)   |      |
| Repro with our demo project  | no           |      |
| Demo project link            | [link to a demo project that highlights the issue ](https://github.com/duguyihou/react-native-turbo-image/pull/256)|      |

### Issue Description and Steps

when i use your library to integrate apng with coil in [this pull request](https://github.com/duguyihou/react-native-turbo-image). Decoder work well with ```disk cache policy```. But Decoder can not get ```ImageSource.file()``` with ```memory cache policy```

**Comment by vokhuyetOz** [comment]
https://github.com/line/apng-drawable can get image inputstream both disk cache policy and memory cache policy

**Comment by penfeizhou** [comment]
Thanks for feedback，I'll check it.

**Comment by vokhuyetOz** [comment]
@penfeizhou  do you have any information about it?

**Comment by RobbWatershed** [comment]
Same problem here - using the following decoder for Coil3

```kt
class AnimatedPngDecoder(private val source: ImageSource) : Decoder {

    override suspend fun decode(): DecodeResult {
        return DecodeResult(
            image = APNGDrawable.fromFile(source.file().toString()).asImage(),
            isSampled = false
        )
    }

    class Factory : Decoder.Factory {
        override fun create(
            result: SourceFetchResult,
            options: Options,
            imageLoader: ImageLoader
        ): Decoder? {
            return if (APNGParser.isAPNG(result.source.file().toString())) {
                AnimatedPngDecoder(result.source)
            } else {
                null
            }
        }
    }
}
```

The Factory runs fine but `decode()` generates the following stacktrace
```
java.io.FileNotFoundException: /data/user/0/me.devsaki.hentoid.debug/cache/tmp_13103856800822388989: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at com.github.penfeizhou.animation.io.FileReader.<init>(FileReader.java:17)
	at com.github.penfeizhou.animation.loader.FileLoader.obtain(FileLoader.java:26)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:302)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:287)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8046)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 10 more
```

**Comment by RobbWatershed** [comment]
FYI, the maintainer of Coil has posted a solution that might answer this question : https://github.com/coil-kt/coil/issues/2557

(at least it helped me fix my own problem)
