### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference

### ISSUE THREAD

**Issue by panpf** [penfeizhou/APNG4Android#228]
### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | arm64 模拟器                               |      |
| System Version               | api 21                                             |      |
| APNG4Android Library Version | 3.0.1                                           |      |

### Issue Description and Steps

我尝试将 awebp 模块集成到我的项目中，用于在 api 28 以下解码 webp 的第一帧，代码如下：

```kotlin
override fun decode(): DecodeResult {
    val streamLoader = dataSource.toStreamLoader(requestContext.request.context)
    val webpDecoder = WebPDecoder(streamLoader, null)
    val bounds = webpDecoder.bounds
    val imageInfo = ImageInfo(
        width = bounds.width(),
        height = bounds.height(),
        mimeType = "image/webp"
    )
    val resize = requestContext.computeResize(imageInfo.size)
    val inSampleSize = calculateSampleSize(
        imageSize = imageInfo.size,
        targetSize = resize.size,
        smallerSizeMode = resize.precision.isSmallerSizeMode()
    )
    val dstSize = Size(
        width = ceil(imageInfo.width / inSampleSize.toFloat()).toInt(),
        height = ceil(imageInfo.height / inSampleSize.toFloat()).toInt()
    )
    webpDecoder.setDesiredSize(dstSize.width, dstSize.height)
    val bitmap = webpDecoder.getFrameBitmap(0)
    val decodeResult = DecodeResult(
        image = bitmap.asImage(),
        imageInfo = imageInfo,
        dataFrom = dataSource.dataFrom,
        resize = resize,
        transformeds = null,
        extras = null,
    )
    val resizeResult = decodeResult.resize(resize)
    return resizeResult
}

fun DataSource.toStreamLoader(context: Context): Loader {
    return when (this) {
        is FileDataSource -> {
            FileLoader(path.toString())
        }

        is ByteArrayDataSource -> {
            object : ByteBufferLoader() {
                override fun getByteBuffer(): ByteBuffer {
                    return ByteBuffer.wrap(data)
                }
            }
        }

        is ContentDataSource -> {
            object : StreamLoader() {
                override fun getInputStream(): InputStream {
                    return context.contentResolver.openInputStream(contentUri)
                        ?: throw IOException("Invalid content uri: $contentUri")
                }
            }
        }

        is AssetDataSource -> {
            AssetStreamLoader(context, fileName)
        }

        is ResourceDataSource -> {
            ResourceStreamLoader(context, resId)
        }

        else -> {
            throw IllegalArgumentException("Unsupported DataSource: ${this::class}")
        }
    }
}
```

上述代码抛出以下错误：

```kotlin
java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference
	at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:131)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:510)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.getFrameBitmap(FrameSeqDecoder.java:552)
	at com.github.panpf.sketch.sample.util.PenfeiZhouAnimatedWebpFirstFrameDecoder.decode(PenfeiZhouAnimatedWebpFirstFrameDecoder.kt:73)
	at com.github.panpf.sketch.decode.internal.EngineDecodeInterceptor.intercept-gIAlu-s(EngineDecodeInterceptor.kt:45)
	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
	at com.github.panpf.sketch.sample.image.PaletteDecodeInterceptor.intercept-gIAlu-s(PaletteDecodeInterceptor.kt:17)
	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
	at com.github.panpf.sketch.transform.internal.TransformationDecodeInterceptor.intercept-gIAlu-s(TransformationDecodeInterceptor.kt:38)
	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
	at com.github.panpf.sketch.cache.internal.ResultCacheDecodeInterceptor.intercept-gIAlu-s(ResultCacheDecodeInterceptor.kt:72)
	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
	at com.github.panpf.sketch.request.PauseLoadWhenScrollingDecodeInterceptor.intercept-gIAlu-s(PauseLoadWhenScrollingDecodeInterceptor.kt:68)
	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
	at com.github.panpf.sketch.request.internal.EngineRequestInterceptor$intercept$decodeResult$1.invokeSuspend(EngineRequestInterceptor.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

测试发现注释掉 webpDecoder.setDesiredSize(dstSize.width, dstSize.height) 这行就不会抛异常

**Comment by freeboub** [comment]
I can confirm that this issue is still present in last release (3.0.2) which is used in expo-image

**Comment by freeboub** [comment]
I was expecting to reproduce the issue with following sample, but I don't reproduce it ...
@panpf maybe do you have a clue to reproduce it ?
I tried your code, but I miss some context :/ 

```JAVA
package com.github.penfeizhou.animation.demo;

import android.app.Activity;
import android.graphics.ImageDecoder;
import android.graphics.Rect;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;

import androidx.annotation.RequiresApi;

import com.bumptech.glide.Glide;
import com.github.penfeizhou.animation.apng.APNGDrawable;
import com.github.penfeizhou.animation.avif.AVIFDrawable;
import com.github.penfeizhou.animation.loader.AssetStreamLoader;
import com.github.penfeizhou.animation.loader.FileLoader;
import com.github.penfeizhou.animation.loader.ResourceStreamLoader;
import com.github.penfeizhou.animation.webp.WebPDrawable;
import com.github.penfeizhou.animation.webp.decode.WebPDecoder;

public class ManualLoadingTestActivity extends Activity {
    @RequiresApi(api = Build.VERSION_CODES.P)
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_apnglib);
        LinearLayout linearLayout = findViewById(R.id.layout);

        AssetStreamLoader resourceLoader = new AssetStreamLoader(this, "wheel.avif");
        AVIFDrawable drawable = new AVIFDrawable(resourceLoader);

        /*
        AssetStreamLoader resourceLoader = new AssetStreamLoader(this, "1.webp");
        WebPDrawable drawable = new WebPDrawable(resourceLoader);
*/
        /*
        AssetStreamLoader resourceLoader = new AssetStreamLoader(this, "apng_detail_guide.png");
        APNGDrawable drawable = new APNGDrawable(resourceLoader);
        */

        Log.d("POST", "bound: " + drawable.getBounds());
        ImageView imageView = new ImageView(this);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        layoutParams.bottomMargin = 50;
        layoutParams.topMargin = 50;
        linearLayout.addView(imageView, layoutParams);
        imageView.setImageDrawable(drawable);
        Handler handler = new Handler(getMainLooper());
        Runnable postInternal = new Runnable() {
            @Override
            public void run() {
                Log.d("POST", "POST");
                //drawable.getFrameSeqDecoder().stop();
                drawable.getFrameSeqDecoder().setDesiredSize(10, 10);
                //drawable.getFrameSeqDecoder().start();
                handler.postDelayed(this,500);
            }
        };
        handler.postDelayed(postInternal,500);
    }
}
```

**Comment by freeboub** [comment]
Notice that my callstack is the following:

NullPointerException
Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference
com.github.penfeizhou.animation.avif.decode.AVIFDecoder in renderFrame at line 114
com.github.penfeizhou.animation.decode.FrameSeqDecoder in step at line 512
com.github.penfeizhou.animation.decode.FrameSeqDecoder in access$200 at line 36
com.github.penfeizhou.animation.decode.FrameSeqDecoder$1 in run at line 60
com.github.penfeizhou.animation.decode.FrameSeqDecoder in innerStart at line 319
com.github.penfeizhou.animation.decode.FrameSeqDecoder in access$1000 at line 36
com.github.penfeizhou.animation.decode.FrameSeqDecoder$6 in run at line 288
android.os.Handler in handleCallback at line 991
android.os.Handler in dispatchMessage at line 102
android.os.Looper in loopOnce at line 232
android.os.Looper in loop at line 317
android.os.HandlerThread in run at line 85

**Comment by penfeizhou** [comment]
> ### Issue Info
> Info	Value	
> Device Info	arm64 模拟器	
> System Version	api 21	
> APNG4Android Library Version	3.0.1	
> ### Issue Description and Steps
> 我尝试将 awebp 模块集成到我的项目中，用于在 api 28 以下解码 webp 的第一帧，代码如下：
> 
> override fun decode(): DecodeResult {
>     val streamLoader = dataSource.toStreamLoader(requestContext.request.context)
>     val webpDecoder = WebPDecoder(streamLoader, null)
>     val bounds = webpDecoder.bounds
>     val imageInfo = ImageInfo(
>         width = bounds.width(),
>         height = bounds.height(),
>         mimeType = "image/webp"
>     )
>     val resize = requestContext.computeResize(imageInfo.size)
>     val inSampleSize = calculateSampleSize(
>         imageSize = imageInfo.size,
>         targetSize = resize.size,
>         smallerSizeMode = resize.precision.isSmallerSizeMode()
>     )
>     val dstSize = Size(
>         width = ceil(imageInfo.width / inSampleSize.toFloat()).toInt(),
>         height = ceil(imageInfo.height / inSampleSize.toFloat()).toInt()
>     )
>     webpDecoder.setDesiredSize(dstSize.width, dstSize.height)
>     val bitmap = webpDecoder.getFrameBitmap(0)
>     val decodeResult = DecodeResult(
>         image = bitmap.asImage(),
>         imageInfo = imageInfo,
>         dataFrom = dataSource.dataFrom,
>         resize = resize,
>         transformeds = null,
>         extras = null,
>     )
>     val resizeResult = decodeResult.resize(resize)
>     return resizeResult
> }
> 
> fun DataSource.toStreamLoader(context: Context): Loader {
>     return when (this) {
>         is FileDataSource -> {
>             FileLoader(path.toString())
>         }
> 
>         is ByteArrayDataSource -> {
>             object : ByteBufferLoader() {
>                 override fun getByteBuffer(): ByteBuffer {
>                     return ByteBuffer.wrap(data)
>                 }
>             }
>         }
> 
>         is ContentDataSource -> {
>             object : StreamLoader() {
>                 override fun getInputStream(): InputStream {
>                     return context.contentResolver.openInputStream(contentUri)
>                         ?: throw IOException("Invalid content uri: $contentUri")
>                 }
>             }
>         }
> 
>         is AssetDataSource -> {
>             AssetStreamLoader(context, fileName)
>         }
> 
>         is ResourceDataSource -> {
>             ResourceStreamLoader(context, resId)
>         }
> 
>         else -> {
>             throw IllegalArgumentException("Unsupported DataSource: ${this::class}")
>         }
>     }
> }
> 上述代码抛出以下错误：
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference
> 	at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:131)
> 	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:510)
> 	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.getFrameBitmap(FrameSeqDecoder.java:552)
> 	at com.github.panpf.sketch.sample.util.PenfeiZhouAnimatedWebpFirstFrameDecoder.decode(PenfeiZhouAnimatedWebpFirstFrameDecoder.kt:73)
> 	at com.github.panpf.sketch.decode.internal.EngineDecodeInterceptor.intercept-gIAlu-s(EngineDecodeInterceptor.kt:45)
> 	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
> 	at com.github.panpf.sketch.sample.image.PaletteDecodeInterceptor.intercept-gIAlu-s(PaletteDecodeInterceptor.kt:17)
> 	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
> 	at com.github.panpf.sketch.transform.internal.TransformationDecodeInterceptor.intercept-gIAlu-s(TransformationDecodeInterceptor.kt:38)
> 	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
> 	at com.github.panpf.sketch.cache.internal.ResultCacheDecodeInterceptor.intercept-gIAlu-s(ResultCacheDecodeInterceptor.kt:72)
> 	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
> 	at com.github.panpf.sketch.request.PauseLoadWhenScrollingDecodeInterceptor.intercept-gIAlu-s(PauseLoadWhenScrollingDecodeInterceptor.kt:68)
> 	at com.github.panpf.sketch.decode.internal.DecodeInterceptorChain.proceed-IoAF18A(DecodeInterceptorChain.kt:48)
> 	at com.github.panpf.sketch.request.internal.EngineRequestInterceptor$intercept$decodeResult$1.invokeSuspend(EngineRequestInterceptor.kt:47)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
> 测试发现注释掉 webpDecoder.setDesiredSize(dstSize.width, dstSize.height) 这行就不会抛异常

这是因为webpDecoder.setDesiredSize(dstSize.width, dstSize.height)  会异步设置frameBuffer为null,导致getFrameBitmap时发生NPE. 
请不要同步先后执行这两个API.
