### ISSUE TITLE
Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#25]
Hey,

When I wanted to debug some crashes I noticed this bug. Is it something that I can fix on my end?

> StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

Here are the full logs

```log
2019-08-17 09:22:43.099 16542-16551/app.fedilab.android D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1803)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
        at java.io.FileInputStream.finalize(FileInputStream.java:487)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:221)
        at java.io.FileInputStream.<init>(FileInputStream.java:168)
        at com.github.penfeizhou.animation.io.FileReader.reset(FileReader.java:24)
        at com.github.penfeizhou.animation.io.FilterReader.toInputStream(FilterReader.java:55)
        at com.github.penfeizhou.animation.io.FilterReader.toInputStream(FilterReader.java:56)
        at com.github.penfeizhou.animation.apng.decode.StillFrame.draw(StillFrame.java:35)
        at com.github.penfeizhou.animation.apng.decode.StillFrame.draw(StillFrame.java:19)
        at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame(APNGDecoder.java:190)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:463)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:35)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784) 
```

**Comment by penfeizhou** [comment]
The Stream would be closed until the drawable is stopped.

**Comment by stom79** [comment]
OK. So I guess an issue with my RecyclerView. What would be the best approach for animated apng with ImageSpan in  RecyclerView.Adapter?

**Comment by stom79** [comment]
OK. Solved on my end. I had an issue with my timer.
