### ISSUE TITLE
File not found exception should stop the animation

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#27]
I noticed when cleaning the cache a bunch of warning:

```log
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.io.FileInputStream.open0(Native Method)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.io.FileReader.reset(FileReader.java:24)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.io.FilterReader.reset(FilterReader.java:30)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.encode(APNGFrame.java:89)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:126)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:22)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame(APNGDecoder.java:190)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:463)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:35)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:56)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-08-24 12:18:14.988 17833-18021/app.fedilab.android W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-08-24 12:18:14.995 17833-18040/app.fedilab.android W/System.err: java.io.FileNotFoundException: /data/user/0/app.fedilab.android/cache/image_manager_disk_cache/5b6ee9e893a2dd423458d69fea72ef028141b23897100f97af8dd83ca2b2e2e5.0 (No such file or directory)
```

The error is handled in `APNGFrame.java`
https://github.com/penfeizhou/APNG4Android/blob/0bc7ef74469a2077b9041bf42b582c54aeb7e3b2/apng/src/main/java/com/github/penfeizhou/animation/apng/decode/APNGFrame.java#L126

Would it be possible to stop the animation especially for the `FileNotFoundException`

**Comment by penfeizhou** [comment]
It seemed that the file is cleaned while animation is playing .This is a situation I did not consider included.
Yes i think it's reasonable to stop animation while file is not founded.
