### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ZeroCandy** [penfeizhou/APNG4Android#49]
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.width()' on a null object reference
        at com.github.penfeizhou.animation.FrameAnimationDrawable.getIntrinsicWidth(FrameAnimationDrawable.java:196)
        at android.widget.ImageView.invalidateDrawable(ImageView.java:293)
        at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:450)
        at android.graphics.drawable.Drawable.setVisible(Drawable.java:859)
        at com.github.penfeizhou.animation.FrameAnimationDrawable.setVisible(FrameAnimationDrawable.java:191)
        at android.widget.ImageView.updateDrawable(ImageView.java:1061)
        at android.widget.ImageView.setImageDrawable(ImageView.java:609)
        at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:28)
        at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:10)
        at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:127)
        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:104)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:582)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:544)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:152)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:398) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) `

**Comment by ZeroCandy** [comment]
加载APNG的时候出现

**Comment by penfeizhou** [comment]
版本号是什么？能否提供下能出现这个问题的PNG图片

**Comment by ZeroCandy** [comment]
`implementation 'com.github.penfeizhou.android.animation:glide-plugin:1.3.1'`

不是特定的APNG图片导致的崩溃，而是使用ViewPager切换Fragment，Fragment是一个图片列表，在切换的过程中出现的异常

**Comment by ZeroCandy** [comment]
> 版本号是什么？能否提供下能出现这个问题的PNG图片
