### ISSUE TITLE
java.lang.OutOfMemoryError on ByteBufferWriter.reset

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#56]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  |Huawei P8 lite 2017 (HWPRA-H)                            |      |
| System Version               | Android 8.0                                   |      |
| APNG4Android Library Version |   1.3.3                                          |      |

### Issue Description and Steps
I only see that error logs and I can't link the call from my project that throws them.

https://github.com/penfeizhou/APNG4Android/blob/0bc7ef74469a2077b9041bf42b582c54aeb7e3b2/frameanimation/src/main/java/com/github/penfeizhou/animation/io/ByteBufferWriter.java#L51

```
java.lang.OutOfMemoryError: 
 
  at java.nio.HeapByteBuffer.<init> (HeapByteBuffer.java:54)
 
  at java.nio.HeapByteBuffer.<init> (HeapByteBuffer.java:49)
 
  at java.nio.ByteBuffer.allocate (ByteBuffer.java:261)
 
  at com.github.penfeizhou.animation.io.ByteBufferWriter.reset (ByteBufferWriter.java:51)
 
  at com.github.penfeizhou.animation.apng.io.APNGWriter.reset (APNGWriter.java:33)
 
  at com.github.penfeizhou.animation.apng.decode.APNGFrame.encode (APNGFrame.java:70)
 
  at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw (APNGFrame.java:126)
 
  at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw (APNGFrame.java:22)
 
  at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame (APNGDecoder.java:190)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step (FrameSeqDecoder.java:451)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200 (FrameSeqDecoder.java:34)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run (FrameSeqDecoder.java:58)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart (FrameSeqDecoder.java:270)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900 (FrameSeqDecoder.java:34)
 
  at com.github.penfeizhou.animation.decode.FrameSeqDecoder$3.run (FrameSeqDecoder.java:240)
 
  at android.os.Handler.handleCallback (Handler.java:808)
 
  at android.os.Handler.dispatchMessage (Handler.java:101)
 
  at android.os.Looper.loop (Looper.java:166)
 
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

**Comment by penfeizhou** [comment]
From this error message,it could because of the high memory usage.You should check system and app memory usage at the moment while this exception occured.

**Comment by stom79** [comment]
I have no controls over images that crash. I wonder if this out of memory error could be handled like it is in other part of the library.

**Comment by penfeizhou** [comment]
OutOfMemory Exception willl cause function not working.

**Comment by stom79** [comment]
Yes, I understand, but handling for avoiding a crash would be better for UX.
I still have crashes like:

```logs
STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a 911429800 byte allocation with 22020815 free bytes and 490MB until OOM, max allowed footprint 44074399, growth limit 536870912
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:281)
	at com.github.penfeizhou.animation.io.ByteBufferWriter.reset(ByteBufferWriter.java:51)
	at com.github.penfeizhou.animation.apng.io.APNGWriter.reset(APNGWriter.java:33)
	at com.github.penfeizhou.animation.apng.decode.APNGFrame.encode(APNGFrame.java:70)
	at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:126)
	at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:22)
	at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame(APNGDecoder.java:190)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:451)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:34)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:58)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:270)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:34)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$3.run(FrameSeqDecoder.java:240)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by jingpeng** [comment]
update to 2.2.0 will fix it
