### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by L-stack-lab** [penfeizhou/APNG4Android#57]
- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | vivo Y66                               |      |
| System Version               | 6.0.1                                             |      |
| APNG4Android Library Version |  1.3.3                                           |      |

java.lang.IllegalArgumentException: Problem decoding into existing bitmap
	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:525)
	at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:133)
	at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:22)
	at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame(APNGDecoder.java:190)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:451)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:34)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:58)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jingpeng** [comment]
Can you paste your image url?

**Comment by L-stack-lab** [comment]
> Can you paste your image url?

感觉跟图片关系不大，不必现，不好重现

**Comment by L-stack-lab** [comment]
> Can you paste your image url?

不确定是不是图片的问题，不必现，本地不好重现，但概率还是蛮大的

**Comment by penfeizhou** [comment]
If you have further information, please provide us.
