### ISSUE TITLE
IOException: mark/reset not supported when using custom StreamLoader

### ISSUE THREAD

**Issue by RobbWatershed** [penfeizhou/APNG4Android#58]
### New Issue Checklist

- [x]  I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | (1) Huawei Honor 8X + (2) Android emu API29
| System Version               | (1) 9.0 + (2) 10.0 |      |
| APNG4Android Library Version | 1.3.3                                           |      |
| Repro rate                   | all the time (100%)|      |
| Repro with our demo project  | not tried            |      |
| Demo project link            | N/A |      |

### Issue Description and Steps

When trying to use the library's `FileLoader`, my images wouldn't be displayed when passing absolute paths located on the SD card. I guess that is because APNG4Android relies on `File` only, and not on SAF.

To fix that, I implemented a custom `StreamLoader` that fetches the proper `InputStream` (see below). 

The problem is, APNG4Android seems to call `InputStream`'s `reset` method without intercepting the `IOException`, resulting in an empty image. 

NB : The problem does not come from the test image I use, because it is properly displayed and animated when located in the phone's memory (the area where `new FileInputStream(file)` works fine).

```java
//                FileLoader loader = new FileLoader(absolutePath):  <-- doesn't work when absolutePath points to a location on the SD card
ImgLoader loader = new ImgLoader(absolutePath);
APNGDrawable apngDrawable = new APNGDrawable(loader);
imgView.setImageDrawable(apngDrawable);
```

```java
// Load the image using an InputStream whatever the location of the path (phone memory or SD card)
static class ImgLoader extends StreamLoader {

        private String path;

        ImgLoader(String path) {
            this.path= path;
        }

        @Override
        protected InputStream getInputStream() throws IOException {
            DocumentFile file = FileHelper.getDocumentFile(new File(path), false); // Helper to get a DocumentFile out of the given File
            if (null == file || !file.exists()) return null; // Not triggered

            return App.getInstance().getContentResolver().openInputStream(file.getUri());
        }
    }
```

**Suggestions**
a. Catch the reported exception (see below) and continue loading the image properly
and/or
b. Use `ContentResolver.openInputStream` inside `FileReader` to support resources located on SAF area. 

```
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err: java.io.IOException: mark/reset not supported
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at java.io.InputStream.reset(InputStream.java:348)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at java.io.FilterInputStream.reset(FilterInputStream.java:226)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.io.StreamReader.reset(StreamReader.java:39)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.io.FilterReader.reset(FilterReader.java:30)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.encode(APNGFrame.java:89)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:126)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGFrame.draw(APNGFrame.java:22)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.apng.decode.APNGDecoder.renderFrame(APNGDecoder.java:190)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:451)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:34)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:58)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-02-23 22:30:02.900 7395-7559/app.debug W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by penfeizhou** [comment]
You can try the code below:
```java
// Load the image using an InputStream whatever the location of the path (phone memory or SD card)
static class ImgLoader implements Loader {

    private String path;

    ImgLoader(String path) {
        this.path = path;
    }

    @Override
    public synchronized Reader obtain() throws IOException {
        return new ImgReader(path);
    }
}

static class ImgReader extends FilterReader {
    private String path;

    private static InputStream getInputStream(String path) throws IOException {
        DocumentFile file = FileHelper.getDocumentFile(new File(path), false); // Helper to get a DocumentFile out of the given File
        if (null == file || !file.exists()) return null; // Not triggered

        return App.getInstance().getContentResolver().openInputStream(file.getUri());
    }

    public ImgReader(String path) throws IOException {
        super(new StreamReader(getInputStream(path)));
        this.path = path;
    }

    @Override
    public void reset() throws IOException {
        reader.close();
        reader = new StreamReader(getInputStream(path));
    }
}
```

You can still use `ImgLoader`.

**Comment by penfeizhou** [comment]
You can customize the Reader generated by your loader and override `reset` method.

**Comment by RobbWatershed** [comment]
Fan-tas-tic. That's exactly what I needed.

Thanks for taking the time to write working code !
