### ISSUE TITLE
load APNG crash using glide-plugin 2.7.0 version

### ISSUE THREAD

**Issue by pssxsy** [penfeizhou/APNG4Android#92]
Caused by: java.lang.ClassCastException: android.graphics.drawable.TransitionDrawable cannot be cast to android.widget.ImageView
        at com.github.penfeizhou.animation.FrameAnimationDrawable.hookRecordCallbacks(FrameAnimationDrawable.java:312)
        at com.github.penfeizhou.animation.FrameAnimationDrawable.setVisible(FrameAnimationDrawable.java:225)
        at android.graphics.drawable.LayerDrawable.setVisible(LayerDrawable.java:1338)
        at android.widget.ImageView.updateDrawable(ImageView.java:1064)
        at android.widget.ImageView.setImageDrawable(ImageView.java:594)
        at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:104)
        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:53)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:57)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:15)
        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:100)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:631)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by penfeizhou** [comment]
Did you use `com.github.penfeizhou.android.animation:glide-plugin`?
From the stack you posted, there's no `hookRecordCallbacks ` in FrameAnimationDrawable.And the line number does not match too.
Please tell me more details for your issue.

**Comment by adbenitez** [comment]
hello @penfeizhou,  I am having this issue, I was trying to enable support for APNG and animated webp to [this app](https://github.com/adbenitez/deltalab-android/) so I added to `build.gradle`:

`implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.9.0'`

And in some parts of the application animated APNG and webp works but in another parts:

```
04-07 00:30:34.166 27923 27923 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                 
04-07 00:30:34.166 27923 27923 E AndroidRuntime: Process: chat.delta.lite, PID: 27923                                                                                  
04-07 00:30:34.166 27923 27923 E AndroidRuntime: com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:161)                    04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)                                                         04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)                                                        04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)                                                                     04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7948)                                        
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)                           04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)                                               04-07 00:30:34.166 27923 27923 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.graphics.drawable.TransitionDrawable cannot be cast to android.widget
.ImageView                                                                                                                                                             
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.github.penfeizhou.animation.FrameAnimationDrawable.hookRecordCallbacks(FrameAnimationDrawable.java:312)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.github.penfeizhou.animation.FrameAnimationDrawable.setVisible(FrameAnimationDrawable.java:225)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.graphics.drawable.LayerDrawable.setVisible(LayerDrawable.java:1338)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.widget.ImageView.updateDrawable(ImageView.java:1062)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at android.widget.ImageView.setImageDrawable(ImageView.java:592)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:104)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:53)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.jav
a:57)                                                                                                                                                                  
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.jav
a:15)                                                                              
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:100)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:639)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:578)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:159)
04-07 00:30:34.166 27923 27923 E AndroidRuntime:        ... 8 more
```

**Comment by jingpeng** [comment]
this is a bug & we will fix it in following commit

**Comment by adbenitez** [comment]
@jingpeng great! looking forward to the next release :rocket:

**Comment by penfeizhou** [comment]
https://github.com/penfeizhou/APNG4Android/commit/9c1609fdb417e5786ee0446a0ea4ae10ced82486
This commit fixed it.

**Comment by adbenitez** [comment]
works like a charm, thanks a lot!
Greetings from Cuba :)
