### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by chenyunecjtu** [penfeizhou/APNG4Android#97]
implementation "com.github.penfeizhou.android.animation:glide-plugin:2.8.0@aar"

glide version : 4.11.0
annotationProcessor "com.github.bumptech.glide:compiler:4.11.0"
api "com.github.bumptech.glide:glide:4.11.0"

```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/penfeizhou/animation/decode/FrameSeqDecoder;
        at com.github.penfeizhou.animation.glide.GlideAnimationModule.registerComponents(GlideAnimationModule.java:29)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:34)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:305)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:242)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:201)
        at com.bumptech.glide.Glide.get(Glide.java:182)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)
        at com.app.presenter.GlideApp.with(GlideApp.java:86)
```

**Comment by penfeizhou** [comment]
Please make sure use following codes.
```groovy
implementation "com.github.penfeizhou.android.animation:glide-plugin:2.8.0"
```
Delete `@aar`.
